### ISSUE TITLE
Add static version of callhorizons to G/MTVT repo

### ISSUE THREAD

**Issue by bholler** [spacetelescope/jwst_gtvt#11]
In order to prevent issues with future updates of the callhorizons package, a dependency for the MTVT, it would be a good idea to include a static version of callhorizons in the G/MTVT repo. Future new features will not be necessary as long as the interface with Horizons remains unchanged.

@mfixstsci identified potential issues with just including the callhorizons repo in the G/MTVT repo, specifically the problem with having two separate setup files that may not interact appropriately with each other.

The callhorizons repo is hosted here: https://github.com/mommermi/callhorizons

_The JDOX page for the MTVT will need to be updated after this work is complete._

**Comment by mfixstsci** [comment]
With the refactoring of the code to use astroquery, should we close this issue?

**Comment by bholler** [comment]
@mfixstsci Yes, now that we are using astroquery this ticket should be closed as irrelevant.
