### ISSUE TITLE
ability and/or docs on `import jwst_gtvt`

### ISSUE THREAD

**Issue by zkbt** [spacetelescope/jwst_gtvt#21]
@nespinoza just gave a great tutorial introducing `jwst_gtvt` at the SEEC symposium on rocky exoplanets with JWST. He mentioned there should be a way I can run it from inside a python script, as in `import gtvt; observable_PAs = gtvt.is_observable(ra, dec, start, end)` or some such. If so, might it please be possible to document how to do that? I'd be super grateful!

**Comment by nespinoza** [comment]
Hi @zkbt, 

 Glad you liked the tool! In case you need this ASAP, the ExoCTK folks import this tool to make their plots in their website and their code is public here: https://github.com/ExoCTK/exoctk/blob/master/exoctk/contam_visibility/visibilityPA.py

 But yes, I agree it would be good to have it documented within the GTVT tool directly if it is not already (I could swear I saw an import of the tool in Jdox, but I might have confused it with th ExoCTK usage).

Best,
Néstor

**Comment by zkbt** [comment]
Thanks, @nespinoza ! No rush -- but from that exoctk snippet it looks pretty simple. Great work today!

**Comment by mfixstsci** [comment]
@zkbt sorry for the long reply. This type of functionality should be showcased in the documentation. @nespinoza thanks for providing the ExoCTK snippet in the mean time. I am overhauling some of the documentation with some code changes I am making when I get the time. I will make sure to add this to the list of things to change.

**Comment by mfixstsci** [comment]
Hey @zkbt we just released the 1.0.0 version of the GTVT and now I am combing through old issues. The code base has been completely refactored and is importable and has some documentation was added to the tool. I know it took a long time to get this done but I hope this might help!
