### ISSUE TITLE
mtvt not displaying figure but not crashing

### ISSUE THREAD

**Issue by ahwofford** [spacetelescope/jwst_gtvt#22]
`jwst_mtvt 4`runs and completes but no figures displayed

**Comment by mfixstsci** [comment]
Hey @ahwofford, I made some changes to the script that does the plotting. To get the changes you can just pull them down and then reinstall the package from source.

1. `cd /your/path/to/jwst_gtvt`
2. `git pull origin master`
3. `python setup.py install`
4. `jwst_mtvt 4`

Let me know if you get any errors or have trouble with any of the steps and I can come meet up with you again. Hopefully this solves the plotting issue.

**Comment by ahwofford** [comment]
Hi Mees,

My path to jwst_gtvt is:
/Users/aidawofford/opt/anaconda3/envs/astroconda/bin/

I cd to it and when I did git pull origin master
I got: fatal: not a git repository (or any of the parent directories): .git

Could you please help with this? Sorry, I am not a frequent GitHub user.

Aida

**Comment by mfixstsci** [comment]
Ahhh, you must have installed it using `pip`. I made the assumption you installed from source. Maybe `pip install jwst_gtvt --upgrade` and see if that will reinstall the software with the changes I made.
