### ISSUE TITLE
coordinate systems & angles

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/jwst_gtvt#24]
Hi - I noticed that you have a number of coordinate system angles hard-coded into the find_tgt_info.py file - see below. Apologies if I'm not understanding ow your code is structured so maybe I'm wrong, but for MIRI this angle is not correct. I haven't checked all the others as I'm not so familiar with the apertures, but I'm pretty sure NIRSpec is wrong too.  I've included a code snippet below for how to pull these numbers from the SIAF directly (they get updated quite regularly). 

```
def main(args, fixed=True):

    table_output=None
    if args.save_table is not None:
        table_output = open(args.save_table, 'w')

    NRCALL_FULL_V2IdlYang = -0.0265
    NRS_FULL_MSA_V3IdlYang = 137.4874
    NIS_V3IdlYang = -0.57
    MIRIM_FULL_V3IdlYang = 5.0152
    FGS1_FULL_V3IdlYang = -1.2508

```

```(astroconda) Sarahs-MacBook-Pro-3:data_files kendrew$ ipython
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pysiaf                                                                                                                                                                         
In [2]: pysiaf.__version__                                                                                                                                                                    
Out[2]: '0.6.2'
In [3]: siaf = pysiaf.Siaf('MIRI')                                                                                                                                                            
In [4]: ap = siaf['MIRIM_FULL']                                                                                                                                                               
In [5]: ap.V3IdlYAngle                                                                                                                                                                        
Out[5]: 4.83425324
```
cc @jaymedina @Johannes-Sahlmann

**Comment by mfixstsci** [comment]
Hey @skendrew -- this is really useful. Any suggestion to make the code more robust is always welcome. You are probably right about the value of the angle being incorrect assuming that the siaf file has been updated recently.

**Comment by skendrew** [comment]
I would definitely recommend always retrieving these numbers from the latest version of the SIAF using the pySIAF package. Via this package you can always know what version of the PRD is being used, and even check the history of the values as they have evolved in different versions. I imagine that would be very useful to run tests when you update the tool. 

It would be an additional package dependence. OTOH I see you're planning to include the GTVT into astroconda; in that case the dependency issue would be taken care of (as pySiaf is in astroconda already).

**Comment by mfixstsci** [comment]
Hey @skendrew I went ahead and made some changes that will need to be reviewed (hopefully we can add them soon):

https://github.com/spacetelescope/jwst_gtvt/pull/26

**Comment by PatrickOgle** [comment]
What is the status of this issue, and does it need to be fixed for the Cycle 1 call?
Does it affect the GTVT output and subsequent observation planning?

**Comment by mfixstsci** [comment]
@PatrickOgle the PR is #26, feel free to give it a review.

**Comment by PatrickOgle** [comment]
Hi Mees and Sarah,


Can we get Sarah to take a look at the fix to the GTVT SIAF issues and let us know if they satisfy her concerns?


What is holding up the pull request, apart from a review? I would rather have someone more knowledgeable

than myself on this issue post a review.


Thanks,

Patrick

________________________________

**Comment by mfixstsci** [comment]
@PatrickOgle I went ahead and added a comment to #26 about the NIRCAM angle which is whats holding up the merge.

**Comment by skendrew** [comment]
Sorry I can't make the call about the NIRCam angle, you'd need to get @JAStansberry to take a look, as NIRCam SIAF point person. Also tagging @dlaw as MIRI SIAF expert. The pysiaf calls are implemented correctly afaict. (You could merge the PR as is of course and push the NIRCam angle update in the next one)

**Comment by dlaw** [comment]
I'm afraid you have tagged the wrong dlaw!

**Comment by drlaw1558** [comment]
pysiaf calls look ok to me; only comment would be that it could be helpful to add a statement such as print('SIAF version: ',pysiaf.JWST_PRD_VERSION) to aid in seeing what SIAF version is in use.  Not sure how that fits in with the workflow of this tool, but it could help debug any issues arising if an old version of pysiaf is installed.
I can't comment on whether it's appropriate to use V2IdlYAng for NIRCam, but if the code really does want that I think you'd have to construct it from the SIAF entry for V3IdlYAng

**Comment by mgennaro** [comment]
NIRCam consulted with the TEL branch and we agree that the mention of "V2IdlYAng" is just a typo and should be "V3IdlYAng" as for all other instruments. There is no special treatment of NIRCam angles in the SIAF. From Matthew Lallo's email to me:

> I don’t see any problem anywhere. The pasted screen snap looks as expected regarding PA-V3 and the NIRCam mosaics and offsets execute as expected  for us on the OTB.
We’re not aware of any special treatment for NIRCam regarding these conventions or definitions. 

Also, given that there are minor discrepancies observed, I commented via email:

> It would be important that you double check that the PA ranges between the GTVT and what displayed in APT are the same, once you start using the up-to-date version of the SIAF, just as a sanity check.

**Comment by skendrew** [comment]
thanks @mgennaro. In that case the GTVT should be able to implement the call to pysiaf for this angle and close the issue.

**Comment by mfixstsci** [comment]
Thanks @mgennaro and @skendrew! I can make  the change, thanks for the update.
