### ISSUE TITLE
Suppress printing in find_tgt_info.get_table?

### ISSUE THREAD

**Issue by seweissman** [spacetelescope/jwst_gtvt#38]
Would it be possible to add an optional parameter to this function to suppress the printing to stdout? We are using this in the exomast web application to generate visibility plots and every time this function is called it's printing a bunch of text to the logs.

https://github.com/spacetelescope/jwst_gtvt/blob/master/jwst_gtvt/find_tgt_info.py#L496

**Comment by mfixstsci** [comment]
Hey @seweissman that should be easy enough to do. I am going to take @jaymedina because she handles this on the ExoCTK end. I can add this here on my end too because I think having a verbose option is a good idea.

**Comment by seweissman** [comment]
Thank you. We are actually currently using this through ExoCTK. Forgot to mention that!

**Comment by mfixstsci** [comment]
@seweissman no worries, I'll make the change so @jaymedina can proceed with the changes on the ExoCTK end. Thanks!

**Comment by mfixstsci** [comment]
Hey All, I am going to go ahead and close this. The changes are in and now it's on the `ExoCTK `. See PR #44
