### ISSUE TITLE
Difficulty pip installing for Python-3.7.7

### ISSUE THREAD

**Issue by jaytmiller** [spacetelescope/jwst_gtvt#45]
I'm trying to pip install for Python-3.7 but getting a dependency error.

```
$ python
Python 3.7.7 (default, Mar 26 2020, 10:32:53)
...
$ pip install jwst-gtvt
ERROR: Could not find a version that satisfies the requirement jwst-gtvt (from versions: none)
ERROR: No matching distribution found for jwst-gtvt
```

I think this is a result of "python_requires<=3.7" in setup.py which surprisingly seems to mean <=3.7.0.   

Assuming you don't really mean <= 3.7.0,  one fix in setup.py is:

```
-
-     python_requires='<=3.7',
+
+     python_requires='<3.8',
```

**Comment by mfixstsci** [comment]
@jaytmiller thanks for reporting this. I will circle back to you when I get a chance to investigate. I believe that you can set the `python_requires` flag to '<=3.7.x' to cover the point releases.

**Comment by mfixstsci** [comment]
Just made a pull request with the `python_requires` to include versions `<=3.7.*`. Go ahead and see if that solves your installation issues and then I can push the changes.

**Comment by privong** [comment]
@mfixstsci Is it possible to extend to python 3.8.x? I haven't done exhaustive testing, but I've built the package myself (changing `setup.py` to allow 3.8.x) and it seems to work fine for general fixed target visibility (by-eye comparisons with target visibilities generated with the tool running under python 3.6.x).

**Comment by mfixstsci** [comment]
@privong I don't expect much would change but supporting python 3.8.x would have to be a bigger discussion. Making small changes, bug fixes and patch releases are in the scope of things I can do independently. I went ahead and opened a separate issue and tagged you along with the software release lead for discussion.

**Comment by mfixstsci** [comment]
Hey All -- another issue worth mentioning is #22! There was a `matplotlib` bug that was causing the mac OS to crash and burn when trying to generate the figure at the end. This is why the `python_version` was set to only include specific versions.

**Comment by privong** [comment]
@mfixstsci Sounds great, thanks.

**Comment by mfixstsci** [comment]
@jaytmiller and @privong I mentioned this in #47 but we now support python versions `3.7`, `3.8` & `3.9`. I will be tagging a release and uploading it to `pypi` today. Sorry this took so long, we chose to freeze for the cycle 1 call. The deadline is long passed and I finally have some time to work on some of these issues, sorry it took this long 😅
