### ISSUE TITLE
Python 3.8.x Support

### ISSUE THREAD

**Issue by mfixstsci** [spacetelescope/jwst_gtvt#47]
Discussion for Python 3.8.x support. @PatrickOgle, in #45 @privong was wondering if we could include support for `python versions >= 3.8.x`. I don't suspect much will change but this will probably be something bigger than a `patch` release so I wanted to start the discussion since it is something we probably be supporting in the future.

**Comment by privong** [comment]
Just wanted to check in on this. I also wanted to note that python 3.9 is out (and 3.10 seems like it'll be hot on its heels): https://pythoninsider.blogspot.com/2020/10/python-390-is-now-available-and-you-can.html.

**Comment by bhilbert4** [comment]
Adding support for 3.8 and 3.9 would be great. The latest releases of the jwst calibration pipeline now are no longer supported for python 3.6. This makes it difficult to create an environment that includes both the calibration pipeline and jwst_gtvt.

**Comment by nflagey-stsci** [comment]
Actually, I think supporting any 3.7 would be enough to solve the issue with the calibration pipeline ...
Right now, we have the calibration pipeline requiring >= 3.7 and jwst_gtvt requiring <=3.7 ... changing the latter to <=3.7.x as suggested in #45 solves the problem

**Comment by mfixstsci** [comment]
Hey All, I am currently in the process of releasing a `v0.2.0` today. The GHA builds currently support `3.7`, `3.8`, & `3.9`. I will go ahead and close this issue unless there is anything else pending.
