### ISSUE TITLE
Update ephemeris for flight

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/jwst_gtvt#67]
Hi @mfixstsci, have you thought yet about updating the target vis tool to use the actual in-flight ephemeris?  We now have an actual 2-year nominal ephemeris from FDF, and it would be nice to update this tool for consistency with the actual orbit we have for real. 

The difference in ephemerides can lead to significant differences in accessible roll angle. Looking at some initial visit files I see differences of several degrees between rolls calculated by gtvt and by PPS (visits that are being produced and are schedulable but look like they may violate sun roll constraint using the ephemeris here)

Not instantly urgent, but something to think about...

**Comment by mfixstsci** [comment]
@mperrin this is something @bholler and @JAStansberry have thought about for a while now. I agree, having the in-flight ephemeris would be ideal, would you be able to email that to me?

One issue we have with this code base is that the `Ephemeris` class (https://github.com/spacetelescope/jwst_gtvt/blob/master/jwst_gtvt/ephemeris_old2x.py#L26) has a custom reader and built in methods that are used in `find_tgt_info.py`. I am thinking that it could be easy enough to rework the class to get the ephemerides on the fly using `astroquery`'s JPL API and set a flag in the `Ephemeris` class to either use the in-flight ephemeris located in the package if there is an issue connecting.

@bholler mentioned that the in-flight emphemerides will updated every 2 weeks, is the ephemeris @mperrin is mentioning different?

**Comment by bholler** [comment]
@mfixstsci If I'm not mistaken, the same 2-year nominal ephemeris was provided to JPL and is available for retrieval in Horizons. The every-other-week updates would be folded into this nominal ephemeris, replacing the placeholder values and resulting in an update the longer-term ephemeris. Something similar is done for HST.

**Comment by mfixstsci** [comment]
Hey @mperrin we just released our v1.0.0 of the GTVT! The newest version grabs the most recent ephemeris from JPL Horizons for JWST on the fly and uses that when the tool is run. I am combing through old issues and closing them. Just wanted to close the loop!
