### ISSUE TITLE
G/MTVT versioning

### ISSUE THREAD

**Issue by bholler** [spacetelescope/jwst_gtvt#8]
@mfixstsci Below is some info I found on "semantic versioning." The website this information came from is here: https://semver.org/.

After reading through this page, I believe that we should set the current version of the G/MTVT to 1.0.0, since 0.1.0 is for development. This tool is in production, so should no longer have an in-development number. But, we should wait until we add the target name to the output for the MTVT, or else that would force us to update to 1.0.1, since that would likely be considered a patch release. Each new update of the ephemeris will increase the minor number by 1.

**Question**: Should we try to keep the minor number on pace with the JWST cycle number, in which case we should artificially bump the version to 1.1.0 prior to the CfP next year, even if there is no JWST ephemeris update?

_**Given a version number MAJOR.MINOR.PATCH, increment the:**
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

**How should I deal with revisions in the 0.y.z initial development phase?**
The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

**How do I know when to release 1.0.0?**
If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0._

**Comment by mfixstsci** [comment]
@bholler With the implementation of the `ins-jwst-community-software` standards https://github.com/spacetelescope/ins-jwst-community-software/#contents we are currently versioning the tool. Going to close this up!
