### ISSUE TITLE
Include G/MTVT in astroconda distribution

### ISSUE THREAD

**Issue by bholler** [spacetelescope/jwst_gtvt#9]
How do we go about including the G/MTVT in astroconda with each new update of the tool? Maybe it is as easy as informing those in charge of maintaining astroconda?

**Comment by mfixstsci** [comment]
The software engineering initiative that started here at ST will take care of the problem you mentioned above. Adding the software to astroconda might be a little overkill for what we are trying to accomplish. We now have the the code up on `pypi` and an `environment.txt` file defined for users if they want to make their own conda environment outside of the extras that come with `astroconda`. I will close this for now but we can always revisit this later.
